import { Inter } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <nav className="w-full bg-teal-400 text-5xl flex justify-center items-center gap-x-10">
          <Link href="/">Home</Link>
          <Link href="/articles">Articles</Link>
          <Link href="/articles/articleOne">ArticleOne</Link>
          <Link href="/posts">Posts</Link>
        </nav>
        {children}
      </body>
    </html>
  );
}
